# netlify.toml
[[redirects]]
    from = "/admin/*"
    to = "/admin/index.html"
    status = 200
    force = true
    conditions = {Role = ["admin", "editor"]}

[build]
    command = "chmod +x build.sh && ./build.sh"
    publish = "dist" # Change this to your SSG output directory

[build.environment]
     NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true"

[functions]
  # This tells Netlify to grab the WASM file from rust-wasm folder 
  # and include it in the SSR function's environment.
  included_files = ["rust-wasm/pkg/*.wasm"]