backend:
  name: github
  repo: lorearchive/law-content
  branch: main
  site_domain: lorearchive.netlify.app
  auth_endpoint: oauth
media_folder: "images"
public_folder: "/images"

collections:
  - name: wiki
    label: The Lore Archives
    folder: content/wiki
    create: false
    extension: "txt"
    slug: "{{title}}"
    fields:
      - { name: body, label: Body, widget: richtext }
