backend:
  name: github
  repo: lorearchive/LAWE
  branch: main
  site_domain: lorearchive.netlify.app
  base_url: https://lorearchive.netlify.app
  auth_endpoint: oauth
  local_backend: true
media_folder: "images"
public_folder: "/images"

collections:
  - name: wiki
    label: The Lore Archives
    folder: content/wiki
    create: false
    extension: "txt"
    slug: "{{title}}"
    fields:
      - { name: body, label: Body, widget: richtext }
