backend:
  name: git-gateway
  branch: main

media_folder: "/images" # Where images are stored
public_folder: "/images"   # The path to access them in the HTML

collections:
  - name: "Lore Archive Wiki"
    label: "Wiki Pages"
    label_singular: "Wiki Page"
    folder: "public/content/wiki"       # raw wikifiles
    create: true               # Allow users to create new files
    slug: "{{slug}}"           # Filename template
    extension: "txt"           # Force .txt extension
    format: "yaml-frontmatter" # Tells CMS to wrap content in YAML
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "code" } 